title: Slider
accept: image/jpeg
fields:
  heading:
    type: text
    label: Encabezado
  text:
    type: textarea
    label: Texto
  boton:
    type: text
    label: Texto de botón
  enlace:
    type: text
    label: Enlace de botón
  alt:
    type: text
    label: Texto alternativo
