title: Servicios

sections:
  parts:
    headline: Secciones
    type: pages
    status: all
    info: "{{ page.intendedTemplate }}"
    image: false
    templates:
      - slider
      - header
      - info
      - service-1
      - service-2
      - cta